Makefileからmigrationとentitiesの生成するコマンドを追加
Zli-UoA/zoo pull request #52
Opened 2024-07-22 05:40 UTC by yuorei

## issue

https://github.com/Zli-UoA/zoo-backend/issues/43

## やったこと
以下のものをMakefileからできるようにしました。

- prismaのmigration
- sea-orm用のentitiesを生成

2024-07-22 05:46 UTC, eraser5th commented on db-schema/Makefile
> +	npm i -D prisma-erd-generator @mermaid-js/mermaid-cli && \
npm iだけでいいのでは？

2024-07-22 05:48 UTC, yuorei commented on db-schema/Makefile
> +	npm i -D prisma-erd-generator @mermaid-js/mermaid-cli && \
fixed

2024-07-25 01:48 UTC, yuorei commented
@eraser5th @kashu-02 コンフリクト直しました

2024-07-25 02:53 UTC, eraser5th commented
@yuorei 
手元で実行したらエラー出た。

```
󰂃 89% 🕙[ 22:50:58 ] ➜  make generate-entities 
gmake -C db-schema generate-entities
gmake[1]: Entering directory '/Users/katotake/Workspace/Works/zli/zoo'
gmake[1]: *** db-schema: No such file or directory.  Stop.
gmake[1]: Leaving directory '/Users/katotake/Workspace/Works/zli/zoo'
gmake: *** [Makefile:7: generate-entities] Error 2
```

backend/db-schemaを読み取りに行けてなさそう。

2024-07-25 04:48 UTC, eraser5th requested changes

2024-07-25 04:48 UTC, eraser5th commented on backend/db-schema/Makefile
> +	-o ../src/entities
@yuorei 
entitiesの吐き出し場所が間違ってる。
`../src/entities`から`./src/entities`に変えれば良さそう

2024-07-25 04:57 UTC, eraser5th commented
SlackのGitHubボットのお試し

2024-07-25 04:58 UTC, yuorei commented on backend/db-schema/Makefile
> +	-o ../src/entities
@eraser5th 
backend/src/entitiesではないですか？

2024-07-25 05:00 UTC, eraser5th commented on backend/db-schema/Makefile
> +	-o ../src/entities
@yuorei
あー、Makefileの理解足りてないので適当言ったかも。
とりあえず、PRのfiles changedを見れば分かる通りbackendの外にsrc/entitiesができているのを直していただけると。

2024-07-25 05:03 UTC, eraser5th commented on backend/db-schema/Makefile
> +	-o ../src/entities
いや、/src/entitiesが生成されてるのはMakefileの問題ではないのか？

2024-07-25 05:04 UTC, yuorei commented on backend/db-schema/Makefile
> +	-o ../src/entities
これはマージした時のミスですね

2024-07-25 05:05 UTC, eraser5th commented on backend/db-schema/Makefile
> +	-o ../src/entities
なるほど、じゃあ消してもらえばOKかな？

2024-07-25 05:06 UTC, eraser5th submitted a review, later dismissed

2024-07-25 05:07 UTC, yuorei commented
マージ禁止

2024-07-25 17:27 UTC, kashu-02 requested changes
READMEの内容をMakefile使うように変えたほうがよい？

2024-07-25 17:27 UTC, kashu-02 commented on backend/db-schema/Makefile
> +	npx prisma migrate deploy
`npx prisma migrate dev --skip-generate`
が正解な気がしてきた

2024-07-26 00:52 UTC, yuorei commented on backend/db-schema/Makefile
> +	npx prisma migrate deploy
なぜ

2024-07-26 05:55 UTC, kashu-02 commented on backend/db-schema/Makefile
> +	npx prisma migrate deploy
https://www.prisma.io/docs/orm/prisma-migrate/workflows/team-development

2024-07-26 05:56 UTC, kashu-02 commented on backend/db-schema/Makefile
> +	npx prisma migrate deploy
--skip-generateはPrisma Clientは不要なため

2024-07-28 12:03 UTC, yuorei commented on backend/db-schema/Makefile
> +	npx prisma migrate deploy
変えました

2024-07-28 12:17 UTC, kashu-02 approved these changes

2024-07-28 13:27 UTC, noharu36 approved these changes
LGTM

2024-07-28 13:27 UTC, noharu36 commented on backend/src/generate/generate.rs
> +pub mod entitys;
スペルミス

2024-07-28 13:28 UTC, eraser5th approved these changes

2024-07-28 13:29 UTC, merged